server:
  port: 9999

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared
        encrypt:
          enabled: true
  profiles:
     active: native
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: ${SERVER_CONFIG_PASSWORD:1a2s3d.qwe}



logstash:
  host: localhost