server:
  port: 8301

#
spring:
  cloud:
    refresh:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    sender:
      type: kafka
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
#
security:
  oauth2:
    client:
      clientId: service-finance
      clientSecret: ${SERVICE_FINANCE_PASSWORD:1a2s3d.qwe}
      accessTokenUri: http://localhost:6666/api/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:6666/api/auth/user/details
#
alphavantage:
  apikey: '{cipher}AQAKSZVKSS8jSHAgOQwfywuXMyYqpXFaWSnCqeUWFtxCBESoE7D8DtM7klgYoEe3aqCF3pKGyPKrkwGejSUsZC+DvhrxlUD4AZAn3IoNyxJPM4X79EzwyRs4B/lnIpIoHNcRICMije1GlkspPBUiE/CBGkAwLYn64OBf7fGUG+nRrO3WWwh9KIemHyQCgD7WFqOPE5/276aVmWkDqdmDlo4JzVmzpy6PvjoBBstDgby6Ni3ECnRKSPJ/2iOQNA+THUI1CVDJtvzINtPmxVjoWwL+gXJxq4IMnJtLD8Dbh3B1IWUN39xF07gwwWKp5GadwnxVKQaETB4Z3mVOVp29morjjAGEJZSiUI3hvjAgasxSt7XBDQF1qdmUNq7bAaK26IbqpfI2/rXAeRnkBU3xIzkX'

feign:
  hystrix:
    enabled:  true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 300000
#
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#
management:
  endpoints:
    WEB:
      exposure:
        include: hystrix.stream,info,health,bus-refresh
#
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:1a2s3d.qwe@localhost:8888/eureka/
  instance:
    hostname: localhost
#
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
#
logstash:
  host: localhost