server:
  port: 7777

spring:
  cloud:
    refresh:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092

turbine:
  appConfig: service-finance,service-analytics
  aggregator:
    clusterConfig: SERVICE-FINANCE,SERVICE-ANALYTICS

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
logging:
  level:
    root: INFO

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:1a2s3d.qwe@localhost:8888/eureka/
  instance:
    hostname: localhost

logstash:
  host: localhost